version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - my-network
    image: samnotlazy/mysql:latest


  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: itestapp-container
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root_password
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - my-network
    image: samnotlazy/app:latest

networks:
  my-network:
    driver: bridge
