version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql  # Use the custom Dockerfile for MySQL
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - my-network


  app:
    build:
      context: .
      dockerfile: Dockerfile.app  # Use the custom Dockerfile for the Java app
    container_name: app-container
    environment:
      DB_HOST: itestmysql  # hostname of the MySQL service
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root_password
    depends_on:
      - mysql
    ports:
      - "8081:8081"  # Adjust based on the Java app’s port
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
