apiVersion: v1
kind: Pod
metadata:
  name: test-shell
spec:
  containers:
    - name: mysql-client
      image: mysql:5.7
      command: ["sleep", "3600"]  # Keeps the container running so you can exec into it
